### ISSUE TITLE
Create Iteration Plan 2

### ISSUE THREAD

**Issue by henrikalbrecht** [henrikalbrecht/I05-Virtuelle-Maschinen#10]
Create an Iteration Plan for the iteration 2

- Iteration plan 02 (@don-ny - #39 )

**Comment by don-ny** [comment]
Iteration plan needs to be updated after new information was provided during coach meeting and due to updated naming scheme for problems:
1) section "Meilensteine" can be removed because it's part of project plan
2) problems have a new naming scheme: **_PRB##: [Problem name]_**
3) Aufgabenzuordnung only need to incorporate a link to Github representing the tasks for the respective iteration
